// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import IngredientFormsController from "./ingredient_forms_controller"
application.register("ingredient-forms", IngredientFormsController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import StepFormsController from "./step_forms_controller"
application.register("step-forms", StepFormsController)
