// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import IngredientFormsController from "./ingredient_forms_controller"
application.register("ingredient-forms", IngredientFormsController)

import StepFormsController from "./step_forms_controller"
application.register("step-forms", StepFormsController)
