inherit_gem:
  rubocop-rails-omakase: rubocop.yml
  rubocop-rspec: config/default.yml

require:
  - rubocop-rspec

Metrics/BlockLength:
  Max: 30

RSpec/LetSetup:
  Enabled: false

RSpec/ExampleLength:
  Max: 8