databases:
  - name: rice-ball-recipe-db
    databaseName: rice_ball_recipe-db
    user: rice-ball-recipe-user
    region: singapore
    plan: basic-256mb

services:
  - type: web
    name: rice-ball-recipe-web
    runtime: docker
    repo: https://github.com/koki-maekawa/rice-ball-recipe
    plan: starter
    region: singapore
    dockerContext: .
    dockerfilePath: ./Dockerfile
    domains:
      - rice-ball-recipe.com
      - www.rice-ball-recipe.com
    autoDeployTrigger: commit
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rice-ball-recipe-db
          property: connectionString
      - key: PORT
        sync: false
      - key: WEB_CONCURRENCY
        sync: false
      - key: RAILS_MASTER_KEY
        sync: false

  - type: worker
    name: rice-ball-recipe-worker
    runtime: docker
    repo: https://github.com/koki-maekawa/rice-ball-recipe
    plan: starter
    region: singapore
    dockerContext: .
    dockerfilePath: ./Dockerfile
    preDeployCommand: bin/rails db:prepare
    dockerCommand: bundle exec rake jobs:work
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rice-ball-recipe-db
          property: connectionString
      - key: PORT
        sync: false
      - key: WEB_CONCURRENCY
        sync: false
      - key: RAILS_MASTER_KEY
        sync: false

  - type: cron
    name: rice-ball-recipe-cron
    runtime: docker
    repo: https://github.com/koki-maekawa/rice-ball-recipe
    plan: starter
    schedule: "0 21 1 * *"
    region: singapore
    dockerContext: .
    dockerfilePath: ./Dockerfile
    preDeployCommand: bin/rails db:prepare
    dockerCommand: bundle exec rails sitemap:refresh
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rice-ball-recipe-db
          property: connectionString
      - key: PORT
        sync: false
      - key: WEB_CONCURRENCY
        sync: false
      - key: RAILS_MASTER_KEY
        sync: false
