services:
  - type: web
    name: rice-ball-recipe-web
    runtime: docker
    repo: https://github.com/koki-maekawa/rice-ball-recipe
    plan: starter
    region: singapore
    dockerContext: .
    dockerfilePath: ./Dockerfile
    domains:
      - rice-ball-recipe.com
      - www.rice-ball-recipe.com
    autoDeployTrigger: commit
    envVars:
      - key: PORT
        sync: false
      - key: WEB_CONCURRENCY
        sync: false
      - key: RAILS_MASTER_KEY
        sync: false

  - type: worker
    name: rice-ball-recipe-worker
    runtime: docker
    repo: https://github.com/koki-maekawa/rice-ball-recipe
    plan: starter
    region: singapore
    dockerContext: .
    dockerfilePath: ./Dockerfile
    startCommand: bin/delayed_job start
    envVars:
      - key: PORT
        sync: false
      - key: WEB_CONCURRENCY
        sync: false
      - key: RAILS_MASTER_KEY
        sync: false

  - type: cron
    name: rice-ball-recipe-cron
    runtime: docker
    repo: https://github.com/koki-maekawa/rice-ball-recipe
    plan: starter
    schedule: "0 21 1 * *"
    region: singapore
    dockerContext: .
    dockerfilePath: ./Dockerfile
    startCommand: bundle exec rails sitemap:refresh
    envVars:
      - key: PORT
        sync: false
      - key: WEB_CONCURRENCY
        sync: false
      - key: RAILS_MASTER_KEY
        sync: false
