envVarGroups:
  - name: env
    envVars:
      - key: PORT
        sync: false
      - key: WEB_CONCURRENCY
        sync: false
      - key: RAILS_MASTER_KEY
        sync: false

services:
  - type: web
    name: rice-ball-recipe-web
    runtime: docker
    repo: https://github.com/koki-maekawa/rice-ball-recipe
    plan: starter
    envVarGroups:
     - env
    region: singapore
    dockerContext: .
    dockerfilePath: ./Dockerfile
    domains:
    - rice-ball-recipe.com
    - www.rice-ball-recipe.com
    autoDeployTrigger: commit

  - type: worker
    name: rice-ball-recipe-worker
    runtime: docker
    repo: https://github.com/koki-maekawa/rice-ball-recipe
    plan: starter
    envVarGroups:
      - env
    region: singapore
    dockerContext: .
    dockerfilePath: ./Dockerfile
    startCommand: bin/delayed_job start

  - type: cron
    name: rice-ball-recipe-cron
    runtime: docker
    repo: https://github.com/koki-maekawa/rice-ball-recipe
    plan: starter
    schedule: "0 21 1 * *"
    envVarGroups:
      - env
    region: singapore
    dockerContext: .
    dockerfilePath: ./Dockerfile
    startCommand: bundle exec rails sitemap:refresh
